name: Repo Freeze Check

# **What it does**: Prevent pull requests from merging during freezes.
# **Why we have it**: Sometimes we need to freeze deployments for various reasons.
# **Who does it impact**: Anyone working on docs.

on:
  workflow_dispatch:
  merge_group:
  # Needed in lieu of `pull_request` so that PRs from a fork can stopped from merging when there's a freeze.
  pull_request_target:
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review
      - unlocked
    branches:
      - main

permissions:
  contents: read

# **IMPORTANT:** Do not change the FREEZE environment variable set here!
# This workflow runs on a recurring basis. To temporarily disable it (e.g.,
# during a docs deployment freeze), add an Actions Secret to the repo settings
# called `FREEZE` with a value of `true`. To re-enable Audit Logs updates, simply
# delete that Secret from the repo settings. The environment variable here
# will duplicate that Secret's value for later evaluation.
env:
  FREEZE: ${{ secrets.FREEZE }}

jobs:
  check-freezer:
    if: ${{ github.repository == 'github/docs-internal' || github.repository == 'github/docs' }}
    name: Prevent merging during deployment freezes
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.0.0

      - name: Fail if repo merges are paused
        if: ${{ env.FREEZE == 'true' && github.event.pull_request.user.login != 'docs-bot' }}
        run: |
          echo 'Merges into the "main" branch on this repo are currently paused!'
          exit 1
